### ISSUE TITLE
Incompatibility with secrets containing nullbytes.

### ISSUE THREAD

**Issue by Jurpp** [00-matt/minitotp#2]
I noticed this bug while using TOTP secrets generated by [Pyotp](https://github.com/pyauth/pyotp#generating-a-secret-key). Generated secrets can sometimes contain nullbytes. This causes the `strlen()` [call in hotp.c](https://github.com/00-matt/minitotp/blob/a41c15e71cfd85c672b5129d3a61e93b7a8b4702/libminitotp/hotp.c#L32-L35) to return an invalid length. I changed the `mtotp_hotp()` and `mtotp_totp()` functions within the library to require `size_t secret_len` as an extra argument and removed the unsafe `strlen()` call.

Examples (more was edited) :
minitotp.h
```
/**
 * @brief Generate a one-time password.
 *
 * This method generates a one-time password as specified by RFC
 * 4226. It uses a pre-shared secret and a counter to generate a
 * unique code.
 *
 * @param secret The preshared secret.
 * @param secret_len The length of the preshared secret.
 * @param counter An 8-byte counter that changes after every
 *                login attempt. Should be synchronised between
 *                client and server.
 * @param length Length of the produced one-time password. Must
 *               be at least 6.
 * @param buf A buffer to store the OTP in. Must be at least
 *            length + 1 bytes.
 *
 * @return The one-time password as an ASCII string.
 */
char *mtotp_hotp(const char *secret, size_t secret_len, uint64_t counter, int length, char *buf);
```
hotp.c
```
char *mtotp_hotp(const char *secret, size_t secret_len, uint64_t counter, int length, char *buf) {
  assert(length >= 6);
  counter = htobe64(counter);
  uint8_t hmac[20];
  hmac_sha1((const uint8_t *)secret, secret_len, (const uint8_t *)&counter,
            sizeof(counter), hmac);

  uint32_t code = mod(dynamic_truncate(hmac), length);

  pad_otp(code, length, buf);

  return buf;
}
```
I would be happy to push the changes but I'm sure it will break the application you've created around the library. Feel free to contact me if you need help fixing this.

**Comment by 00-matt** [comment]
Hi, thanks for filing an issue. Not sure how I never ran into this while
testing, I must have gotten very lucky/unlucky. :P

For now I think I'll fix this by creating `mtotp_hotp_l` and
`mtotp_totp_l` methods that take in a length. I'll also edit the command
line tool to accept different encodings (hex, base64, etc.) so that they
are capable of handing NUL chars too.

**Comment by Jurpp** [comment]
> Hi, thanks for filing an issue. Not sure how I never ran into this while testing, I must have gotten very lucky/unlucky. :P For now I think I'll fix this by creating `mtotp_hotp_l` and `mtotp_totp_l` methods that take in a length. I'll also edit the command line tool to accept different encodings (hex, base64, etc.) so that they are capable of handing NUL chars too.

Lucky in that case ;) Sounds like a great fix! Please keep me updated!
